### ISSUE TITLE
Add Code bar Reader

### ISSUE THREAD

**Issue by Jupoulet** [Jupoulet/yuka_pregnancy_app#5]
Add code bar reader able to read and paste code bar to the main input.

**Comment by Jupoulet** [comment]
https://openbase.com/js/qr-scanner/documentation

**Comment by Jupoulet** [comment]
https://openbase.com/js/@zxing/library/documentation

**Comment by Jupoulet** [comment]
https://openbase.com/js/react-webcam-barcode-scanner

**Comment by antoineSoros** [comment]
Looks like [react-webcam-barcode-scanner](https://openbase.com/js/react-webcam-barcode-scanner) is no longer working in React 17 project 😞  [Issue #24](https://github.com/jamenamcinteer/react-qr-barcode-scanner/issues/24#issue-1086846457)

**Comment by baimMN** [comment]
great!!!, thank you
